const express = require('express')
const { getSingleYarnDetails, createYarnDetails, updateYarnDetails, removeYarnDetails } = require('../../../Controller/yarnDetailsController/yarnDetailsController')
const { yarnRecevied, receivedYarnDeleted, yarnRetruned } = require('../../../Controller/yarnDetailsController/yarnInformationController/yarnInfoWithDetails')
const { protect } = require('../../../Middlewares/protectMiddleware')
const router = express.Router()
router.get('/api/order/yarn/details/:id',protect,getSingleYarnDetails)
router.post('/api/order/yarn/details',protect,createYarnDetails)
router.post('/api/order/yarn/received',protect,yarnRetruned)
router.post('/api/order/yarn/received/remove/:id',protect,receivedYarnDeleted)
router.patch('/api/order/yarn/details/:id',protect,updateYarnDetails)
router.delete('/api/order/yarn/details/:id',protect,removeYarnDetails)
module.exports=router