const express = require('express')
const { getAllOrder, findOrderWithPo, getSingleOrder, createOrder, updateOrder, removeOrder, getSingleOrderQuantityInfo, getAllOrderForInvoice, getSingleOrderForEdit} = require('../../Controller/OrderController/orderController')
const { protect } = require('../../Middlewares/protectMiddleware')
const router = express.Router()
router.get('/api/order',protect,getAllOrder)
router.get('/api/v1/order',protect,getAllOrderForInvoice)
router.get('/api/order/:id',protect,getSingleOrder)
router.get('/api/edit/order/:id',protect,getSingleOrderForEdit)
router.get('/api/quantity/order/:id',protect,getSingleOrderQuantityInfo)
router.post('/api/order',protect,createOrder)
router.patch('/api/order/:id',protect,updateOrder)
router.delete('/api/order/:id',protect,removeOrder)
router.post('/api/v1/order/invoice',protect,findOrderWithPo)

module.exports=router